Portfolio: finish mobile version
jossi30/Portfolio pull request #2
Opened 2022-12-02 20:39 UTC by jossi30

added a works and about me sections to the mobile version

2022-12-02 22:36 UTC, Gambit142 requested changes
Hi @jossi30 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- All linters checks passed ✔️ 
- Descriptive pull request title ✔️ 

## Required Changes ♻️
### I am suggesting these changes here because I can not make inline comments on the README.md file. 👍 

Kindly make the following changes in your `README.md` file:
- [ ] Remove the `Usage`, `Run Tests`, `Deployment` and Install sections of the file since they are irrelevant to this project. Also, remove the corresponding tabs in the **_Table of Content_**. 👍 
- [ ] In the **_Tech Stack_** section, kindly remove the _**Server**_ and _**Database**_ subsection. Those stacks are not being used in this project. 👍 
- [ ] For future projects, kindly use imperative tense when typing your commit messages. For example, "**_Change_** the code to use hooks" rather than "**_Changed_** the code to use hooks" 👍 

_Kindly check the comments under the review for other required changes._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-12-02 22:36 UTC, Gambit142 commented on index.html
> +        </section>
- [ ] Kindly use `display: grid;` to align all children elements of this section. Remember that it is one of the requirements for this project. 👍

2022-12-02 22:36 UTC, Gambit142 commented on index.html
> +            <div class="recent">My Recent <br>Works</div>
- [ ] Kindly use one of the `hx` tags (h2-h6) for this element instead of the `div` element. It is more semantic to use the `hx` tag. 👍

2022-12-02 22:36 UTC, Gambit142 commented on style.css
> +}
- [ ] One of the major requirements for this milestone is to use _**flexbox**_ to align items for each card. Kindly change to _**flexbox**_ instead of _**grid**_

2022-12-02 22:36 UTC, Gambit142 commented on index.html
> +                <div class="pr-name">Multi-Post Stories Gain+Glory</div>
- [ ] Kindly use one of the `hx` tags (h2-h6) for this element instead of the `div` element. It is more semantic to use the `hx` tag. 👍

2022-12-02 22:36 UTC, Gambit142 commented on style.css
> +}
- [ ] The color of this element is `#3A4A42` based on the template you chose. Kindly use it. 👍

2022-12-02 22:36 UTC, Gambit142 commented on style.css
> +}
- [ ] Add interactions for this button element The interactions you will need to implement are for the hover, active and pressed states. For example:

```CSS
.see-btn:hover {
  color: blue;
  background-color: white;
}
```

Please don't use the values I used for the properties declared above. You can find the properties and values to be used when you inspect the Figma template you chose. A snapshot is attached to guide you to the section

![image](https://user-images.githubusercontent.com/77106962/205400064-4256fd1b-d8d2-4b9e-ac0b-b7c8c06a9198.png)

![image](https://user-images.githubusercontent.com/77106962/205400123-e3ceb437-5a9b-46c4-a860-782d6bd6c49c.png)

Choose one of them and implement it 👍

2022-12-02 22:36 UTC, Gambit142 commented on index.html
> +          <div class="abt">About me</div>
- [ ] Kindly use one of the `hx` tags (h2-h6) for this element instead of the `div` element. It is more semantic to use the `hx` tag. 👍

2022-12-02 22:36 UTC, Gambit142 commented on index.html
> +            don’t hestiate to contact me.</div>
- [ ] Kindly use one of the `p` tags for this element instead of the `div` element. It is more semantic to use the `p` tag. 👍

2022-12-02 22:36 UTC, Gambit142 commented on style.css
> +}
- [ ] Kindly refer to the inline comment ... that I made regarding interactions for the button element. 💻

2022-12-02 22:36 UTC, Gambit142 commented on style.css
> +}
- [ ] Kindly use the flexbox to align this section based on this milestone's requirement. 👍

2022-12-03 17:39 UTC, levy002 requested changes
## Hello @jossi30   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 17:39 UTC, levy002 commented on index.html
> +                <div class="pr-name"><h3>Multi-Post Stories Gain+Glory</h3></div>
- [ ] As requested by the previous reviewer, kindly make sure to use the heading tag for the title of each project.

2022-12-03 17:39 UTC, levy002 commented on index.html
> +          <div class="abt">About me
- [ ] As requested by the previous reviewer, kindly use the heading tag for the `About me` title.

2022-12-03 17:39 UTC, levy002 commented on style.css
> +}
- [ ] Kindly make sure to align your background image correctly in order to meet the project requirement. :wink: 
- [ ] Kindly make sure to align your content using the flexbox as requested by the previous reviewer. :wink: 

   - ### YOUR DESIGN
      ![image](https://user-images.githubusercontent.com/87197412/205453962-a1b2897c-0f05-4faa-b492-adfe0ab318fe.png)


   - ### FIGMA DESIGN
     ![image](https://user-images.githubusercontent.com/87197412/205453967-37ac9dd6-fc73-4760-a708-69ddd10aa32d.png)

2022-12-03 20:09 UTC, Ugboaja-Uchechi approved these changes
Hi @jossi30, 

## Status: APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Linters are passing ✔️ 
- README is descriptive 👍 
- Great job with your design and functionalities 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 20:11 UTC, merged