Portfolio: desktop version
jossi30/Portfolio pull request #5
Opened 2022-12-09 20:40 UTC by jossi30

adding a desktop version to the mobile layout of the portfolio page

2022-12-09 21:44 UTC, Gambit142 requested changes
Hi @jossi30 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- Most of the Desktop version was implemented correctly ✔️ 
- Descriptive Pull Request Title ✔️ 
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

#### I am making this suggestion here because I can't make inline comments on the README.md file. 

Kindly make the following changes to the README.md file:

- [ ] Kindly remove the Microverse logo. If you have your logo, you can use it in place of the Microverse logo, if not, kindly remove it. 👍
- [ ] In the Tech Stack section, kindly remove the server and database subsection. These subsections are not needed because you didn't use servers or databases in this project. 👍

- [ ] Populate the following sections with the relevant information:
 
- Getting Started: In this section, kindly populate information for the following subsection
  - Prerequisites
  - Setup
  - Install
  - Usage
- Future Features: In the Future Features section, include 1 - 3 features that can be implemented in this project. They will serve as a guide for collaboration in the future

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:

#### It would be nice to fill the **FAQ** section of your README.md file with information. 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-12-09 21:44 UTC, Gambit142 commented on index.html
> +                        </div>
- [ ] Great work implementing the input for both the first and last names. Unfortunately, the requirements state that you should use one input instead of two inputs. The single input should have the placeholder Full name just the same way you did with your mobile version. 👍 

![image](https://user-images.githubusercontent.com/77106962/206796740-32e6d040-5631-432c-9a5b-ebea84784536.png)

2022-12-09 21:44 UTC, Gambit142 commented on index.html
> +                      </div>
- [ ] On both the `desktop` and `mobile` versions of the Framework div, there is a background image overlapping this subsection. Kindly fix it and make your design identical to that of the Figma template you chose. 👍 

### Your Design - Desktop

![image](https://user-images.githubusercontent.com/77106962/206797363-251055f6-7344-4580-ac40-add9fbb1c86a.png)

### Figma Design - Desktop

![image](https://user-images.githubusercontent.com/77106962/206797446-79699526-4b68-4ff0-be5f-b60e4c6fa21c.png)

### Your Design - Mobile

![image](https://user-images.githubusercontent.com/77106962/206797708-a498f447-418d-4fe5-9645-81c4243eab26.png)

### Figma Design - Mobile

![image](https://user-images.githubusercontent.com/77106962/206797822-5813f5a6-7a2f-47fa-8279-cc558de8cefc.png)

2022-12-09 21:44 UTC, Gambit142 commented on index.html
> +                        </div>
- [ ] The form is overlapping some text in the background. Kindly remove the text in the background. 👍 

### Your Design

![image](https://user-images.githubusercontent.com/77106962/206798184-d602fb64-f5ab-4a25-8eb4-e52f16f4a8c3.png)

### Figma Design

![image](https://user-images.githubusercontent.com/77106962/206798394-04a4498d-25fb-4063-b34a-b398b6f31041.png)

2022-12-09 21:44 UTC, Gambit142 commented on index.html
> +                      <p> I can help you build a product , feature or website Look through some of my work and<br> experience! If you like what you see and have a project you need coded,<br> don’t he
- [ ] I notice that this `p` element is not identical to that of the Figma template that you chose on the mobile version. Kindly make them identical so that your design looks really good n the mobile version. The text in it is spread across 6 lines on Figma but yours is spread across 8 lines. 👍 

### Your Design

![image](https://user-images.githubusercontent.com/77106962/206799171-4ff252d2-306e-492e-abb7-50e87fe4cf85.png)

### Figma Template

![image](https://user-images.githubusercontent.com/77106962/206799261-5f5fe4ef-bc88-4ebc-afd6-9b46aa78fbab.png)

2022-12-10 09:48 UTC, Favourezeugwa commented on index.html
> +                          </div>
- Great Job implementing the contact form `name` field as just `Full name` alone 💪🏽 

- I believe this image `<img id="img2" src="img/frame.png" alt="">` is causing a bug in your portfolio both on mobile and desktop screen. Can we remove it and replace it with the right image. Guess you may need to download it from Figma because you currently do not have it on your `img` folder. 🤗 

- This bug may have affected your contact form in some way as well.

Just as @Gambit142 has commented, Here is what I can see 👇🏽 

| Your Desktop screen|
| :---:   | 
|![deskbd](https://user-images.githubusercontent.com/99246359/206845268-e87a62f0-9d45-45eb-aab1-203a06e391f0.PNG)  |

|Your mobile screen |
| :---:   | 
|![mobbd](https://user-images.githubusercontent.com/99246359/206845327-fb05d3f3-2e9c-4337-90ad-5b93dfec1011.PNG)  |


- As soon as you replace the image, the bug will be fixed. 🌸

2022-12-10 10:15 UTC, Nyame-Wolf approved these changes
# STATUS: APPROVED :heavy_check_mark: :green_circle: 

Hi @jossi30  :smile: , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://media.giphy.com/media/l4q7TIW8nEZYOJUf6/giphy.gif)


## Highlights :sparkles:
- Linters are passing
- Has made changes required
## Optional suggestions :ballot_box_with_check: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

APPROVED! 💯 💯 💯

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me, @Nyame-Wolf in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-10 10:16 UTC, merged